export { default as card } from './card.png';
export { default as card1 } from './card1.png';
export { default as card2 } from './card2.png';
export { default as card3 } from './card3.png';
export { default as card4 } from './card4.png';
export { default as card5 } from './card5.png';
export { default as card6 } from './card6.png';
export { default as card7 } from './card7.png';
export { default as card8 } from './card8.png';
export {default as avto1} from './avto1.png';
export {default as avto2} from './avto2.png';
export {default as avto3} from './avto3.png';
export {default as avto4} from './avto4.png';
export {default as valentina} from './valentina.png';
export {default as oleg} from './oleg.png';
export {default as irina} from './irina.png';
export {default as user} from './avatar.png';
export {default as frame} from './Frame.png';
export {default as frame1} from './Frame1.png';
export {default as frame2} from './Frame2.png';
export {default as frame3} from './Frame3.png';
export {default as frame4} from './Frame4.png';
export {default as frame5} from './Frame5.png';